
on:
  - push
jobs:
  deploy:
    name: Backup Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Create bundle 
      run: git clone --mirror https://github.com/chireddy/chireddy.git chireddy.git && cd chireddy.git && git bundle create chireddy.bundle --all
    - name: Create a backup directory and move the bundle
      run: mkdir chireddy_backup && cd chireddy.git && cp *.bundle /chireddy_backup
    - name: show all
      run: cd chireddy.git && ls -la 
      
    - name: Verify the Backup folder
      run: cd chireddy_backup && ls -la
